### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by rramachandra-ucsd**

### CODE REVIEW

**Comment by rramachandra-ucsd** [comment]
Weather data notebook initial update

**Comment by shaneluna** [comment]
- rename -> 3_process_weather_aggregation
- Can you add summary to top of notebook describing what it does?
- update weather_data_file_path to be pointed to the output of the last notebook in processed instead of your local c drive-- /data/processed/<insert weather file name>
- use new /data/processed/camera_image_id_mappings.csv instead of camera_id_mappings file

**Comment by shaneluna** [comment]
@iperezx Just a heads up, I think this is the last PR (or potentially second to last).

**Comment by iperezx** [comment]
Can you store this file somewhere (repo or nautilus s3): `camera_station_mapping2 = pd.read_csv("../../data/raw/camera_id_mapping.csv")`. I am not able to run this cell since it is missing.

Updated my comment because I was looking at the wrong cell.

**Comment by shaneluna** [comment]
@rramachandra-ucsd I just merged you're changes into 1 PR so we can just focus here.

Changes to make:
- 03_weatherdata_aggregation.ipynb --> rename to 3_process_weather_aggregation.ipynb
- weather_data_file_path should not point to your c drive as absolute path; repoint to relative path to the /data/processed/ folder
- remove camera_id_mappings file; pull latest changes from main and repoint that path to /data/processed/camera_station_mappings.csv <br>**(this file was created last week to try and keep as much manual input in the manual single manual file and then script the generation of this file to limit the amount of manual files to manage)**
- Additionally, add markdown summary to top of notebook describing what it is doing

**Comment by shaneluna** [comment]
Merged changes from https://github.com/shaneluna/smokeynet-engineering/pull/25

**Comment by shaneluna** [comment]
- Add summary to top of notebook
- Typo correction: "Merge both the mappnig files" -> "Merge both the mapping files"

**Comment by shaneluna** [comment]
@iperezx I haven't heard back from Ravi on adding some documentation/summary to notebook (last thing that was needed). Are you okay without that for now? :/
If yes, can approve and merge into main

**Comment by iperezx** [comment]
yes that is fine. I can add it later.

**Review by iperezx — APPROVED** [review]

**Pull request merged**
